import "@/app/globals.css";
import useMovie from "@/hooks/useMovie";
import type { Metadata } from "next";

async function getData(params: any) {
  const data = await fetch(`http://localhost:3000/api/movies/${params}`);
  return data.json();
}

export async function generateMetadata({ params }: any): Promise<Metadata> {
  const dataMovie = getData(params);
  console.log(dataMovie);
  return {
    title: "Watch: NontonMoal✨",
    description: "Generated by create next app",
  };
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
